import book from '../assets/img/kenzbook.png';
import creative from '../assets/img/creative.jpeg';
import app from '../assets/img/app.jpeg';
import kinz from '../assets/img/kinz.jpeg';
import { HiMiniComputerDesktop } from 'react-icons/hi2';
import { RiComputerFill } from 'react-icons/ri';
import { SiInternetcomputer } from 'react-icons/si';
import { GiComputerFan } from 'react-icons/gi';

export const courses = [
  {
    id: 1,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'minning',
    rating: 3.4,
    img: book,
  },
  {
    id: 2,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'minning',
    rating: 3.4,
    img: book,
  },
  {
    id: 3,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'minning',
    rating: 3.4,
    img: book,
  },
  {
    id: 4,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'minning',
    rating: 3.4,
    img: book,
  },
  {
    id: 5,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'programming',
    rating: 3.4,
    img: creative,
  },
  {
    id: 6,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'programming',
    rating: 3.4,
    img: creative,
  },
  {
    id: 7,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'programming',
    rating: 3.4,
    img: creative,
  },
  {
    id: 8,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'programming',
    rating: 3.4,
    img: creative,
  },
  {
    id: 9,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'programming',
    rating: 3.4,
    img: creative,
  },
  {
    id: 10,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'lang',
    rating: 3.4,
    img: kinz,
  },
  {
    id: 11,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'lang',
    rating: 3.4,
    img: kinz,
  },
  {
    id: 12,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'digitalMarkiting',
    rating: 3.4,
    img: app,
  },
  {
    id: 13,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'digitalMarkiting',
    rating: 3.4,
    img: app,
  },
  {
    id: 14,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'digitalMarkiting',
    rating: 3.4,
    img: app,
  },
  {
    id: 15,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'digitalMarkiting',
    rating: 3.4,
    img: app,
  },
  {
    id: 16,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'digitalMarkiting',
    rating: 3.4,
    img: app,
  },
  {
    id: 17,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 ',
    price: 150,
    desc: 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    catigory: 'digitalMarkiting',
    rating: 3.4,
    img: app,
  },
];
export const services = [
  {
    id: 1,
    title: ' التدريب والتطوير',
    description:
      'نقدم برامج تدريبية مخصصة لمساعدتك في اكتساب المهارات والمعرفة اللازمة لنجاحك في مجال الأعمال والتجارة الإلكترونية. سواء كنت تحتاج إلى تطوير مهارات القيادة، إدارة المشاريع، التسويق الرقمي أو أي مجال آخر، فإن فريقنا من المدربين المحترفين مستعد لمساعدتك',
    button: 'قدم الان',
    icon: `<HiMiniComputerDesktop />`,
  },
  {
    id: 2,
    title: ' بناء متجر الكترونى',
    description:
      'نقدم برامج تدريبية مخصصة لمساعدتك في اكتساب المهارات والمعرفة اللازمة لنجاحك في مجال الأعمال والتجارة الإلكترونية. سواء كنت تحتاج إلى تطوير مهارات القيادة، إدارة المشاريع، التسويق الرقمي أو أي مجال آخر، فإن فريقنا من المدربين المحترفين مستعد لمساعدتك',
    button: 'احصل الان',
    icon: `<RiComputerFill />`,
  },
  {
    id: 3,
    title: ' LLC  تأسيس شركة أمريكية',
    description:
      'نحن نعلم بالصعوبات والتعقيدات في فتح بوابة الدفع في أغلب الدول العربية ، لذلك نساعدك في فتح شركة أمريكية محدودة المسؤولية مع حساب بنكي أمريكي عالمي خلال مدة إسبوع ',
    button: 'اطلب الان',
    icon: `<SiInternetcomputer />`,
  },
  {
    id: 4,
    title: ' المشوره فى التجاره الالكترونيه',
    description:
      'إذا كنت ترغب في بدء مشروع التجارة الإلكترونية الخاص بك، فنحن هنا لنقدم لك الإرشاد والدعم اللازمين. سنساعدك في فهم أفضل النماذج التجارية، اختيار المنصة المناسبة، تطوير خطة التسويق الرقمي وتحقيق نجاح متجرك الإلكتروني.',
    button: 'حجز استشاره',
    icon: "GiComputerFan",
  },
];
